#!/usr/bin/env bash
# Remove only the local state generated by deploy-app for one app project.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: reset.sh <app-project-path> [--yes]

Removes local deploy-app state so the next deploy-app run starts its setup
again. This removes:
  .deploy-app.env
  .deploy-app.env.example
  .app-store-submit.env
  .deploy-app-state
  store-metadata/

It does not delete the Xcode project, screenshots, previews, privacy-policy
source, or anything already created in App Store Connect.

Pass --yes to skip the confirmation prompt.
EOF
}

fail() {
  printf 'deploy-app reset: %s\n' "$*" >&2
  exit 1
}

case "${1:-}" in
  --help|-h|'') usage; exit 0 ;;
esac

[[ $# -le 2 ]] || { usage >&2; exit 2; }
project_input="$1"
assume_yes=0
if [[ "${2:-}" == "--yes" ]]; then
  assume_yes=1
elif [[ $# -eq 2 ]]; then
  fail "Unknown option: $2"
fi

project_dir="$(cd "$project_input" 2>/dev/null && pwd -P)" || fail "Project directory not found: $project_input"
[[ "$project_dir" != "/" ]] || fail "Refusing to reset the filesystem root"

targets=(
  "$project_dir/.deploy-app.env"
  "$project_dir/.deploy-app.env.example"
  "$project_dir/.app-store-submit.env"
  "$project_dir/.deploy-app-state"
  "$project_dir/store-metadata"
)

existing=()
for target in "${targets[@]}"; do
  [[ -e "$target" || -L "$target" ]] && existing+=("$target")
done

if [[ ${#existing[@]} -eq 0 ]]; then
  printf 'deploy-app reset: no generated deployment state found in %s.\n' "$project_dir"
  exit 0
fi

printf 'The following local deploy-app artifacts will be removed:\n'
printf '  %s\n' "${existing[@]}"
if [[ "$assume_yes" == 0 ]]; then
  [[ -t 0 ]] || fail "Use --yes when running without an interactive terminal"
  read -r 'reply?Continue? [y/N] '
  [[ "$reply" =~ ^[Yy]([Ee][Ss])?$ ]] || { printf 'deploy-app reset: cancelled.\n'; exit 0; }
fi

rm -rf -- "${existing[@]}"
printf 'deploy-app reset: cleared local deployment state for %s.\n' "$project_dir"
